server:
  port:
    8080

spring:
  application:
    name: spring cloud gateway
  cloud:
    gateway:
      routes:
        - id: test_service1
          uri: http://localhost:8081
          predicates:
            - Path=/service1/**
          filters:
            - name: CircuitBreaker
              args:
               name: testCircuitBreaker
               fallbackUri: forward:/fallback

        - id: test_service2
          uri: http://localhost:8082
          predicates:
            - Path=/service2/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

resilien
