server:
  port:
    8080

spring:
  application:
    name: spring cloud gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 2s
      routes:
        - id: test_service1
          uri: http://localhost:8081
          predicates:
            - Path=/service1/**
          filters:
            -name: CircuitBreaker

        - id: test_service2
          uri: http://localhost:8082
          predicates:
            - Path=/service2/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
 circuitbreaker:
  configs:
    default:
      failureRateThreshold: 50
      slowCallRateThreshold: 100
      slowCallDurationThreshold: 60000
      permittedNumberOfCallsInHalfOpenState: 4
      maxWaitDurationInHalfOpenState: 1000
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 10000
  instances:
    customCircuitBreaker:
      baseConfig: default